version: "3"
services:
  api:
    image: node:latest
    ports:
      - 3000:3000
    environment:
      - DB_CONNECTION=mongodb://apex-admin:apex-pass@db:27017
      - DB_NAME=apexdb
    volumes:
      - type: bind
        source: ./api
        target: /code
    working_dir: /code
    command: "bash", "-c", "npm install && npm run dev"
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=apex-admin
      - MONGO_INITDB_DATABASE=apexdb
      - MONGO_INITDB_ROOT_PASSWORD=apex-pass
    volumes:
      - "dbdata:/var/lib/mongodb/data"

volumes:
  dbdata:
